feat(db): prune lite node data automatically
tronprotocol/java-tron pull request #5105
Opened 2023-03-31 03:57 UTC by lurais

**What does this PR do?**
Prune lite node data automatically
**Why are these changes required?**

**This PR has been tested by:**
- Unit Tests
- Manual Testing

**Follow up**

**Extra details**

2023-04-03 08:15 UTC, lurais commented on chainbase/src/main/java/org/tron/core/db2/core/SnapshotRoot.java
> +    ChainDataPruner.register(this.db.getDbName(), this);
In fact it has no effect.

2023-04-03 09:53 UTC, lurais commented on chainbase/src/main/java/org/tron/common/storage/prune/ChainDataPruner.java
> +  private long BLOCKS_TO_RETAIN = 65536;
ok

2023-04-10 09:53 UTC, halibobo1205 requested changes

2023-04-10 09:53 UTC, halibobo1205 commented on framework/src/test/java/org/tron/common/storage/prune/ChainDataPrunerTest.java
> +      ReflectUtils.setFieldValue(chainDataPruner,"blocksToRetain",3);
why by reflect

2023-04-10 09:53 UTC, halibobo1205 commented on framework/src/main/java/org/tron/core/net/message/handshake/HelloMessage.java
> +    if (!chainBaseManager.isLiteNode()) {
check lite first before autoPrune

2023-04-10 09:53 UTC, halibobo1205 commented on framework/src/main/java/org/tron/core/net/message/handshake/HelloMessage.java
> +  }
refactoring code for easy understanding

2023-04-10 09:53 UTC, halibobo1205 commented on framework/src/main/java/org/tron/core/config/args/Args.java
> +        Storage.getDbAutoPruneFrequencyFromConfig(config));
deal  it in storage

2023-04-10 09:53 UTC, halibobo1205 commented on chainbase/src/main/java/org/tron/core/db2/core/SnapshotRoot.java
> +  private static final Set<String> PRUNE_DBS = Arrays.asList( "block-index","block", "trans",
move to ChainDataPruner

2023-04-10 09:53 UTC, halibobo1205 commented on chainbase/src/main/java/org/tron/common/storage/prune/ChainDataPruner.java
> +        Math.min((latestBlockNumber - lowestBlockNumber + 1 - blocksToRetain), blocksBatchFlush);
performance？

2023-04-10 11:27 UTC, halibobo1205 requested changes

2023-04-10 11:27 UTC, halibobo1205 commented on framework/src/main/java/org/tron/core/net/message/handshake/HelloMessage.java
> +  }
return Math.Max(latestBlockNum - retainBlocksSafeIn2Days + 1, lowestBlockNum)?

2023-04-14 13:02 UTC, 317787106 approved these changes

2023-04-17 05:26 UTC, halibobo1205 approved these changes

2023-04-17 06:42 UTC, guoquanwu approved these changes

2023-04-17 06:57 UTC, merged